title: Aahlad Manas Puli
author: Aahlad Manas Puli
logo: /assets/img/aahlad.jpg
description: Assistant Professor / Faculty Fellow at the Center for Data Science, NYU.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Blog: "Every Other Epoch"
permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed

feed:
  path: /blog/feed.xml

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
